### ISSUE TITLE
Kubernetes Liveness Probe via Helm

### ISSUE THREAD

**Issue by vpatil-tibco** [TIBCOSoftware/be-tools#136]
Add support for kubernetes liveness probe. As part of the config, use the existing jmx port for a tcpsocket check.

The values.yml should simply have an enable/disable option for this configuration. Config is added only if it is enabled. Port should be used off whatever port is specified for jmx. Will apply to both inference and cache engines.

**Comment by rameshpolishetti** [comment]
This enhancement is available at - https://github.com/TIBCOSoftware/be-tools/tree/docker-scripts-improvements

Refer to values.yaml below section to enable liveness & readiness probes:

```
# Required for cache and inference agent health check
healthcheck:
  enabled: false        #Set to true - to enable healthcheck
  livenessProbe:
    port: 5555
    initialDelaySeconds: 5
    periodSeconds: 5
  readinessProbe:
    port: 5555
    initialDelaySeconds: 5 
    periodSeconds: 5
```
