### ISSUE TITLE
Update yaml scripts for AWS provider as apiVersion mentioned in those files are no longer supported

### ISSUE THREAD

**Issue by jgirase-tibco** [TIBCOSoftware/be-tools#93]
Below errors are observed when trying to use existing yaml scripts from kubernetes folder to run deployments on AWS,
error: unable to recognize "manifest.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"

After updating apiversion to apps/v1, it shows below error,

error validating "manifest.yaml": error validating data: ValidationError(Deployment.spec): missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by nareshkumarthota** [comment]
try updatng manifest.yaml with below content under deployment section

```yaml
.
.
.
.
kind: Deployment
apiVersion: apps/v1
metadata:
  name: efs-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: efs-provisioner
  strategy:
    type: Recreate
.
.
.
.
```
